@extends('statamic::layout')
@section('title', $name)

@section('content')
<div class="aip">
    <div class="aip-header">
        <div>
            <h1 class="aip-title">{{ $name }}.md</h1>
            <p class="aip-meta aip-mono" style="margin-top:.375rem">{{ $path }}</p>
        </div>
        <a href="{{ cp_route('ai-pages.instructions') }}" class="aip-link">Back</a>
    </div>

    @if ($generated)
        <x-ai-pages::notice type="warning">
            This file is regenerated by the sweep, so edits here are lost next time you run it. For changes that
            must stick, put them in <code class="aip-inline">house-rules.md</code> — that one always wins and is
            never overwritten.
        </x-ai-pages::notice>
    @endif

    <form method="POST" action="{{ cp_route('ai-pages.instructions.update', $name) }}">
        @csrf
        @method('PATCH')

        <div class="aip-card">
            <textarea name="contents" rows="34" class="aip-textarea aip-textarea--mono">{{ $contents }}</textarea>
        </div>

        <button type="submit" class="aip-btn aip-btn--primary">Save</button>
    </form>
</div>
@endsection
