@extends('statamic::layout')
@section('title', $name)

@section('content')
<div class="max-w-4xl">
    <div class="flex items-center justify-between mb-2">
        <h1>{{ $name }}.md</h1>
        <a href="{{ cp_route('ai-pages.instructions') }}" class="text-sm text-blue-600 hover:underline">Back</a>
    </div>

    <p class="text-xs text-gray-500 mb-6 font-mono">{{ $path }}</p>

    @if ($generated)
        <x-ai-pages::notice type="warning">
            This file is regenerated by the sweep, so edits here are lost next time you run it.
            For changes that must stick, put them in <code>house-rules.md</code> — that one always wins and is
            never overwritten.
        </x-ai-pages::notice>
    @endif

    <form method="POST" action="{{ cp_route('ai-pages.instructions.update', $name) }}">
        @csrf
        @method('PATCH')

        <div class="card p-4 mb-4">
            <textarea name="contents" rows="30" class="input-text font-mono text-xs leading-relaxed">{{ $contents }}</textarea>
        </div>

        <button type="submit" class="btn-primary">Save</button>
    </form>
</div>
@endsection
